---
title: "Gov 50 Final Project"
author: "Alex Ankai"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Milestone 2

I am interested in exploring data related to horror films from the last decade to asses box office and budget. My goal would be to push for more creativity in horror films, as opposed to films dependent on algorithms thought to bring in the most money.

Does budget affect horror movie audience engagement? In this study, I plan to analyze the extent to which a horror movie budget affects its viewership and popularity. I hypothesize that a bigger budget brings in a higher number of viewers because more money can be used on advertising, but I think that budget will have little to no correlation with the rating. Horror is a genre of film that is particularly good at making good quality low-budget films, and so I think audience approval will not depend on how much money it took to create a film. However, I think even among low-budget films, there may be a "minimum budget" threshold, below which any film is more likely to be both less viewed and less approved of. I'm going to combine two data sets from IMDb: IMDb Horror: Chilling Movie Dataset, and IMDB Horror Movie Dataset [2012 Onwards]. From the latter, I will observe the variable Budget. From the former, I will take three variables as my outcome variables: Rating (IMDb rating), Votes (number of IMDb votes), and Gross (gross revenue). If movies with a higher budget tend to have a higher number of votes and gross revenue, then the first part of my hypothesis will be correct, that a bigger budget will increase audience engagement. If the Rating variable doesn't increase or decrease when the budget increases, then I will also be correct about a higher budget not necessarily increasing audience approval. If rating does have any significant correlation, then I will be wrong, and budget will either have a positive or negative correlation with audience approval. If Votes and/or Gross have either no correlation with Budget or a negative one, then I will be wrong, and budge has either a negative effect on audience engagement or no effect. I'm unsure how I will observe through data whether a film is a "cult classic" and/or has a cult following.


```{r}

library(distill)
create_article("article.Rmd")
```

